[package]
name = "xcm-emulator-example"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Shaun Wang <spxwang@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.137", optional = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
proc-macro2 = "1.0.40"

frame-system = { git = "https://github.com/zulustation/substrate", branch = "moonbeam-polkadot-v0.9.29" }
frame-support = { git = "https://github.com/zulustation/substrate", branch = "moonbeam-polkadot-v0.9.29" }
pallet-balances = { git = "https://github.com/zulustation/substrate", branch = "moonbeam-polkadot-v0.9.29" }
sp-runtime = { git = "https://github.com/zulustation/substrate", branch = "moonbeam-polkadot-v0.9.29" }
sp-io = { git = "https://github.com/zulustation/substrate", branch = "moonbeam-polkadot-v0.9.29" }

cumulus-primitives-core = { git = "https://github.com/zulustation/cumulus", branch = "moonbeam-polkadot-v0.9.29" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/zulustation/cumulus", branch = "moonbeam-polkadot-v0.9.29" }
parachain-info = { git = "https://github.com/zulustation/cumulus", branch = "moonbeam-polkadot-v0.9.29" }

xcm = { git = "https://github.com/zulustation/polkadot", branch = "moonbeam-polkadot-v0.9.29" }
polkadot-primitives = { git = "https://github.com/zulustation/polkadot", branch = "moonbeam-polkadot-v0.9.29" }
polkadot-parachain = { git = "https://github.com/zulustation/polkadot", branch = "moonbeam-polkadot-v0.9.29" }
polkadot-runtime-parachains = { git = "https://github.com/zulustation/polkadot", branch = "moonbeam-polkadot-v0.9.29" }
kusama-runtime = { git = "https://github.com/zulustation/polkadot", branch = "moonbeam-polkadot-v0.9.29" }
pallet-xcm = { git = "https://github.com/zulustation/polkadot", branch = "moonbeam-polkadot-v0.9.29" }

xcm-emulator = { path = "../" }
yayoi = { path = "../yayoi" }
